# Use the faster container-based infrastructure
# https://docs.travis-ci.com/user/ci-environment/
sudo: false

language: python

python:
    - 2.7
    - 3.4
    - 3.5

env:
    - DJANGO="Django>=1.7,<1.8"
    - DJANGO="Django>=1.8,<1.9"
    - DJANGO="Django>=1.9,<1.10"
    - DJANGO="Django>=1.10,<1.11"

matrix:
    exclude:
        # Python 3.5 is not supported by Django 1.7
        - python: 3.5
          env: 'DJANGO="Django>=1.7,<1.8"'

install:
    - pip install $DJANGO "pytest>3.0"
    # Useful for debugging
    - pip freeze

script: pytest

# Can discuss again if somebody wants them.
notifications:
    email: false
