image: Visual Studio 2019

init:
- net start MSSQL$SQL2019

environment:
  matrix:
    - TOXENV: py36-dj22-mssql
    - TOXENV: py37-dj22-mssql
    - TOXENV: py38-dj22-mssql
    - TOXENV: py39-dj22-mssql
    - TOXENV: py36-dj30-mssql
    - TOXENV: py37-dj30-mssql
    - TOXENV: py38-dj30-mssql
    - TOXENV: py39-dj30-mssql
    # Tests for Django 3.1 and higher disabled because of https://github.com/ESSolutions/django-mssql-backend/pull/86
    # TODO re-enable these after the fix is released.
    # - TOXENV: py36-dj31-mssql
    # - TOXENV: py37-dj31-mssql
    # - TOXENV: py38-dj31-mssql
    # - TOXENV: py39-dj31-mssql

matrix:
  fast_finish: true

install:
  - C:\Python36\python -m pip install tox

build: false  # Not a C# project

test_script:
  - C:\Python36\scripts\tox
