services:
  - mssql2016

environment:
  matrix:
    - TOXENV: py36-dj111-mssql
    - TOXENV: py36-dj20-mssql
    - TOXENV: py36-dj21-mssql

matrix:
  fast_finish: true

install:
  - C:\Python36\python -m pip install tox

build: false  # Not a C# project

test_script:
  - C:\Python36\scripts\tox
